import { Box, Button, Icon, IconProps } from "@alex-mcgovern/boondoggle.design";
import "@alex-mcgovern/boondoggle.design/dist/index.css";
import {
  faHome,
  faList,
  faSpinner,
  faTable,
} from "@fortawesome/pro-solid-svg-icons";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Box
          as="nav"
          padding="space_2"
          background="tint_default"
          borderBottom="border_default"
        >
          <Button
            as={Link}
            href="/"
            slotLeft={<Icon icon={faHome as IconProps["icon"]} />}
            appearance="navigational"
            name="home"
          >
            Home
          </Button>
          <Button
            as={Link}
            href="/form"
            slotLeft={<Icon icon={faList as IconProps["icon"]} />}
            appearance="navigational"
            name="form"
          >
            Form
          </Button>
          <Button
            as={Link}
            href="/data-table"
            slotLeft={<Icon icon={faTable as IconProps["icon"]} />}
            appearance="navigational"
            name="data_table"
          >
            DataTable
          </Button>
          <Button
            as={Link}
            href="/loading"
            slotLeft={<Icon icon={faSpinner as IconProps["icon"]} spin />}
            appearance="navigational"
            name="loading"
          >
            Loading
          </Button>
        </Box>
        {children}
      </body>
    </html>
  );
}
